//Create a user
POST http://localhost:3030/users
Content-Type: application/json

{
    "name": "Pancho1",
    "email": "pancho1@gmail.com",
    "password": "110pancho",
    "confPassword": "110pancho",
    "role": "user"
}

################################################
// Get all users
GET http://localhost:3030/users

######################################
//get Single user
GET http://localhost:3030/users/0ea76051-cd9c-4bf0-8447-fad761ffbf85

######################################
// Update a user
PATCH http://localhost:3030/users/0ea76051-cd9c-4bf0-8447-fad761ffbf85
Content-Type: application/json

{
    "name": "Pancho 12",
    "email": "panch12@gmail.com",
    "password": "12pancho",
    "confPassword": "12pancho",
    "role": "user"
}

######################################
// Delete a user
DELETE http://localhost:3030/users/3ec9591c-1e4e-45eb-ad0e-37dade7ebcdd
#################################################
//Login user
POST http://localhost:3030/login
Content-Type: application/json

{
    "email": "socialsenit@gmail.com",
    "password": "toor"
    
}

######################################
// Logout user
DELETE http://localhost:3030/logout

######################################
// My user
GET http://localhost:3030/me
